# # Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
# fos_elastica:
#     clients:
#         default: { url: '%env(ELASTICSEARCH_URL)%' }
#     indexes:
#         app: null



fos_elastica:
    clients:
        default: { host: vps.latelier22.fr, port: 9200 }

