liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public/'
                    # - '%kernel.project_dir%/public/media/image'
                    # - '%kernel.project_dir%/public/media/image'
                    # - '%kernel.project_dir%/public/media/banner-image'
                    # - '%kernel.project_dir%/public/media/vendor-logo'
                    # - "%sylius_core.public_dir%/media/image"
                    # - "%sylius_core.public_dir%/media" # Add media folder