liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public/'
                    # - '%kernel.project_dir%/public/media/image'
                    # - '%kernel.project_dir%/public/media/image'
                    # - '%kernel.project_dir%/public/media/banner-image'
                    # - '%kernel.project_dir%/public/media/vendor-logo'
                    # - "%sylius_core.public_dir%/media/image"
                    # - "%sylius_core.public_dir%/media" # Add media folder



    filter_sets:
        odiseo_sylius_banner_plugin_image:
            data_loader: banner_image
            filters:
                thumbnail: { size: [1127, 350], mode: outbound }
        odiseo_sylius_banner_plugin_mobile_image:
            data_loader: banner_image
            filters:
                thumbnail: { size: [540, 146], mode: outbound }


        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: inset }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: inset }
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [260, 260], mode: inset }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: inset }