sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_ui:
    events:
        app.admin.hiboutik.dashboard.cards:
            blocks:
                hiboutik_cards:
                    template: "@SyliusAdmin/Dashboard/_hiboutik_cards_event.html.twig"
                    priority: 100

