monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type: firephp
            level: info
        error_log:
            type: stream
            path: "%kernel.logs_dir%/dev-error.log"
            level: error
            channels: ["!event"] 
