asdoria_bulk_edit:
    resource: "@AsdoriaSyliusBulkEditPlugin/config/routing.yaml"

    prefix: /admin

shop_taxon_mis_en_avant:
    path: /{_locale}/taxons/mis-en-avant

app_export_data_taxon:
    path: /admin/export/sylius.resource/csv
    methods: [GET]
    defaults:
        resource: sylius.taxon
        _controller: sylius.controller.export_data_taxon:exportAction
        _sylius:
            filterable: true
            grid: sylius_admin_taxon

admin_export_taxons_csv:
    path: /admin/export/taxons.csv
    controller: App\Controller\Admin\TaxonExportController::exportTaxons


admin_dashboard_rachat_statistics:
    path: /admin/dashboard/rachats/stats
    controller: App\Controller\Admin\Dashboard\RachatStatisticsController::renderRachatStatistics
